### ISSUE TITLE
Add External Triggers for integration with other workflows

### ISSUE THREAD

**Issue by deanishe** [stuartcryan/advanced-google-maps-alfred-workflow#6]
This workflow would integrate very nicely with other workflows that deal with locations.

For example, calendar workflows like my [Google Calendar one](https://github.com/deanishe/alfred-gcal) could pass event locations to this workflow instead of just to Apple/Google Maps.

Would you consider adding the necessary External Triggers to enable that?

**Comment by stuartcryan** [comment]
I had never considered that actually. I will admit I have no experience in the area but it sounds like it would be of great benefit.

If I did this just for the dir command (considering everything else can be achieved with that and passing the right parameters) would that be sufficient?

#openToTheIdea

**Comment by stuartcryan** [comment]
All righty, I had a bit of a look at this today.

In hindsight I realised that there is actually significant benefit in having this across all existing flows.

To do - update the maps command, because currently you can only do directions i.e. you can't just open a single address in Google maps, which could be beneficial.

However, I wanted to check if this is the sort of thing you were thinking?

Version 1.3.1_Alpha1 - https://web.tresorit.com/l#hIlK5OTmq2nCCJpll9q3ig (link expires in 90 days, quite deliberately)

Look forward to your thoughts.

**Comment by deanishe** [comment]
> you can't just open a single address in Google maps.

True, but that's trivially easy to do. It's the directions aspect that makes this workflow attractive to integrate with.

> is the sort of thing you were thinking?

Exactly. Fallback Searches might also be a good idea, so users can just enter or paste an address straight into Alfred, and up pops a `Get Directions to "the address you entered"` item.

**Comment by stuartcryan** [comment]
> you can't just open a single address in Google maps.
>True, but that's trivially easy to do. It's the directions aspect that makes this workflow attractive to integrate with.

*nods* very valid point!

I also hadn't had a chance to play with Fallback Searches before, I will put a new issue in for that, as I like it too!

**Comment by stuartcryan** [comment]
All righty, this is now in 2.0.0_Alpha1. 

Available for your viewing pleasure at https://web.tresorit.com/l#YF3ytbK9g9R7joJZ4m20xg

Twill be a week or so until I am happy enough to release this, as it has had some MAJOR overhauls and needs testing, but let me know your thoughts. I am going to be looking at doing some improvement things as well but this has everything on your wish list.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Also, forgot to mention, there are a couple of notes in the workflow readme next to the workflow environment variables on the new options.

**Comment by stuartcryan** [comment]
ALL RIGHTY! This has been completed and is ready to roll. V2.0.0 Release IMPENDING!!!

(I highly recommend as soon as I do a read of the README page :D #coolNewThingsInbound, though if you just switch to the develop branch you can see it all now!)
