### ISSUE TITLE
Fallback location for "dirfc" command

### ISSUE THREAD

**Issue by deanishe** [stuartcryan/advanced-google-maps-alfred-workflow#8]
With a mind to the integration mentioned in #6, it would be great if the `dirfc` command fell back to a default, user-specified location if `CoreLocationCLI` fails (perhaps `home` or `work` or somewhere else).

CoreLocation depends on WiFi. If you're connected via ethernet, it doesn't work.

**Comment by stuartcryan** [comment]
CoreLocation does depend on WiFi, in thinking how you could do this, I could either provide the option to use home/work (i.e. set to one of the existing locations) or set up an entirely separate location.

Which might tickle your fancy more? (I may be able to do some creative thinking if you just put 'home' in that it would auto translate, I will have a ponder on that a bit more).

I would be curious for how you would see this working well in your best case scenario in your mind.

**Comment by deanishe** [comment]
Personally, I'd go with a separate setting for the fallback location, but one which understands the special values "home" and "work".

I wonder if the workflow variables sheet is the best place for the setting (those values get synced between machines)?

In my case, that would work, as I have a desktop at home (no WiFi), and my notebook only has WiFi. But what if someone has a desktop at home, but connects their notebook to ethernet at work? They would presumably want the first machine to default to "home" and the second to "work".

**Comment by stuartcryan** [comment]
Good to know, I like that thinking to.

Hmm in line with our other thinking on where to store settings I will keep this in mind in thinking how best to handle syncable and non syncable settings.

You have raised a very good point with this one and I will put some more thought in, on the fallback, the ethernet, and definitely the syncing of these settings between devices when difference may be needed.

**Comment by stuartcryan** [comment]
This has now been committed in to the develop branch. Forgot to reference the ticket in the commit #myBad.

**Comment by stuartcryan** [comment]
All righty, this is now in 2.0.0_Alpha1.

Available for your viewing pleasure at https://web.tresorit.com/l#YF3ytbK9g9R7joJZ4m20xg

**Comment by deanishe** [comment]
Lovely. Very nice indeed!

As soon as it's released, I'll update my Google Calendar workflow to link to it.

**Comment by stuartcryan** [comment]
ALL RIGHTY! This has been completed and is ready to roll. V2.0.0 Release IMPENDING!!!

(I highly recommend as soon as I do a read of the README page :D #coolNewThingsInbound, though if you just switch to the develop branch you can see it all now!)
